"""Red tests for /projects endpoints — WU-6.

All tests use async_client_with_db (from conftest) which:
  - Applies migrations to a tmp DB
  - Overrides get_settings to point at tmp_db_path + tmp_projects_root
  - Wraps the app in httpx.AsyncClient via ASGITransport

make_fake_project fixture creates <root>/<domain>/<project>/ dirs
for the path validation to succeed.
"""

import pytest
from httpx import AsyncClient

# ---------------------------------------------------------------------------
# POST /projects — happy paths
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_post_happy_201(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """POST with valid name + path returns 201 and all six fields."""
    project_path = make_fake_project("sandbox", "my-project")
    resp = await async_client_with_db.post(
        "/projects", json={"name": "My Project", "path": str(project_path)}
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["name"] == "My Project"
    assert body["slug"] == "my-project"
    assert body["domain"] == "sandbox"
    assert body["path"] == str(project_path)
    assert body["id"]
    assert body["created_at"]


@pytest.mark.anyio()
async def test_post_auto_slug(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """name without slug → slug auto-generated by slugify."""
    project_path = make_fake_project("sandbox", "cool-project")
    resp = await async_client_with_db.post(
        "/projects", json={"name": "My Cool Project", "path": str(project_path)}
    )
    assert resp.status_code == 201
    assert resp.json()["slug"] == "my-cool-project"


@pytest.mark.anyio()
async def test_post_custom_slug(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """Explicit slug in request body is stored verbatim."""
    project_path = make_fake_project("sandbox", "some-project")
    resp = await async_client_with_db.post(
        "/projects",
        json={"name": "Some Project", "path": str(project_path), "slug": "custom-slug"},
    )
    assert resp.status_code == 201
    assert resp.json()["slug"] == "custom-slug"


# ---------------------------------------------------------------------------
# POST /projects — path validation errors
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_post_path_not_exist_400(
    async_client_with_db: AsyncClient, tmp_projects_root
) -> None:
    """Non-existent path → 400 path_does_not_exist."""
    bad_path = tmp_projects_root / "sandbox" / "no-such-dir"
    resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(bad_path)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "path_does_not_exist"


@pytest.mark.anyio()
async def test_post_path_not_dir_400(
    async_client_with_db: AsyncClient, tmp_projects_root
) -> None:
    """Path is a file → 400 path_not_a_directory."""
    domain_dir = tmp_projects_root / "sandbox"
    domain_dir.mkdir()
    file_path = domain_dir / "a-file.txt"
    file_path.write_text("hello")
    resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(file_path)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "path_not_a_directory"


@pytest.mark.anyio()
async def test_post_outside_root_400(
    async_client_with_db: AsyncClient, tmp_path
) -> None:
    """Path outside projects root → 400 path_outside_projects_root."""
    outside = tmp_path / "totally-outside" / "project"
    outside.mkdir(parents=True)
    resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(outside)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "path_outside_projects_root"


@pytest.mark.anyio()
async def test_post_wrong_depth_one_level_400(
    async_client_with_db: AsyncClient, tmp_projects_root
) -> None:
    """Path only 1 level under root → 400 path_wrong_depth."""
    domain_dir = tmp_projects_root / "sandbox"
    domain_dir.mkdir()
    resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(domain_dir)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "path_wrong_depth"


@pytest.mark.anyio()
async def test_post_wrong_depth_three_levels_400(
    async_client_with_db: AsyncClient, tmp_projects_root
) -> None:
    """Path 3 levels deep → 400 path_wrong_depth."""
    deep = tmp_projects_root / "sandbox" / "project" / "sub"
    deep.mkdir(parents=True)
    resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(deep)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "path_wrong_depth"


# ---------------------------------------------------------------------------
# POST /projects — slug validation errors
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_post_empty_slug_400(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """name '!!!' slugifies to '' → 400 empty_slug."""
    project_path = make_fake_project("sandbox", "some-project")
    resp = await async_client_with_db.post(
        "/projects", json={"name": "!!!", "path": str(project_path)}
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "empty_slug"


@pytest.mark.anyio()
async def test_post_missing_name_returns_400_validation_error(
    async_client_with_db: AsyncClient, make_fake_project
) -> None:
    """Body missing required 'name' → 400 with validation_error envelope (REQ-5)."""
    project_path = make_fake_project("sandbox", "proj")
    resp = await async_client_with_db.post(
        "/projects", json={"path": str(project_path)}
    )
    assert resp.status_code == 400
    body = resp.json()
    assert body["error"]["code"] == "validation_error"
    assert isinstance(body["error"]["message"], str)
    assert isinstance(body["error"]["details"], dict)
    assert body["error"]["details"]  # non-empty


# ---------------------------------------------------------------------------
# POST /projects — duplicate
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_post_duplicate_409(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """Creating the same (domain, slug) twice → 409 conflict_domain_slug."""
    project_path = make_fake_project("sandbox", "my-app")
    payload = {"name": "My App", "slug": "my-app", "path": str(project_path)}
    resp1 = await async_client_with_db.post("/projects", json=payload)
    assert resp1.status_code == 201

    resp2 = await async_client_with_db.post("/projects", json=payload)
    assert resp2.status_code == 409
    assert resp2.json()["error"]["code"] == "conflict_domain_slug"


# ---------------------------------------------------------------------------
# GET /projects
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_get_list_empty(async_client_with_db: AsyncClient) -> None:
    resp = await async_client_with_db.get("/projects")
    assert resp.status_code == 200
    assert resp.json() == {"projects": []}


@pytest.mark.anyio()
async def test_get_list_order(async_client_with_db: AsyncClient, make_fake_project) -> None:
    """Newer project must appear first (created_at DESC)."""
    path_a = make_fake_project("sandbox", "proj-a")
    path_b = make_fake_project("sandbox", "proj-b")

    r1 = await async_client_with_db.post(
        "/projects", json={"name": "A", "slug": "a", "path": str(path_a)}
    )
    r2 = await async_client_with_db.post(
        "/projects", json={"name": "B", "slug": "b", "path": str(path_b)}
    )
    assert r1.status_code == 201
    assert r2.status_code == 201
    id_a = r1.json()["id"]
    id_b = r2.json()["id"]

    resp = await async_client_with_db.get("/projects")
    projects = resp.json()["projects"]
    assert len(projects) == 2
    # B was created second, should come first
    assert projects[0]["id"] == id_b
    assert projects[1]["id"] == id_a


# ---------------------------------------------------------------------------
# GET /projects/{id}
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_get_single_200(async_client_with_db: AsyncClient, make_fake_project) -> None:
    project_path = make_fake_project("sandbox", "proj-x")
    create_resp = await async_client_with_db.post(
        "/projects", json={"name": "X", "path": str(project_path)}
    )
    project_id = create_resp.json()["id"]

    resp = await async_client_with_db.get(f"/projects/{project_id}")
    assert resp.status_code == 200
    assert resp.json()["id"] == project_id


@pytest.mark.anyio()
async def test_get_single_404(async_client_with_db: AsyncClient) -> None:
    resp = await async_client_with_db.get("/projects/nonexistent-id")
    assert resp.status_code == 404
    assert resp.json()["error"]["code"] == "not_found"


# ---------------------------------------------------------------------------
# DELETE /projects/{id}
# ---------------------------------------------------------------------------


@pytest.mark.anyio()
async def test_delete_204(async_client_with_db: AsyncClient, make_fake_project) -> None:
    project_path = make_fake_project("sandbox", "proj-to-delete")
    create_resp = await async_client_with_db.post(
        "/projects", json={"name": "Delete Me", "path": str(project_path)}
    )
    project_id = create_resp.json()["id"]

    delete_resp = await async_client_with_db.delete(f"/projects/{project_id}")
    assert delete_resp.status_code == 204

    get_resp = await async_client_with_db.get(f"/projects/{project_id}")
    assert get_resp.status_code == 404


@pytest.mark.anyio()
async def test_delete_404(async_client_with_db: AsyncClient) -> None:
    resp = await async_client_with_db.delete("/projects/nonexistent-id")
    assert resp.status_code == 404
    assert resp.json()["error"]["code"] == "not_found"
