"""VapidKeysRepository — singleton table for the server VAPID keypair.

Spec: REQ-3 (SC-3.1–3.5)
The table CHECK(id=1) enforces singleton at DB level. INSERT OR IGNORE handles
concurrent first-boot races: second writer's INSERT is silently ignored and
the first writer's row is returned.
"""

from __future__ import annotations

import sqlite3
from collections.abc import Callable
from contextlib import AbstractContextManager
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel

from claude_remote.services.vapid_keygen import generate_keypair


class VapidKeys(BaseModel):
    id: int  # always 1 (CHECK constraint at DB level)
    public_key: str  # URL-safe base64 (browser applicationServerKey format)
    private_key: str  # PEM-encoded EC private key
    created_at: str


ConnectionFactory = Callable[[], AbstractContextManager[sqlite3.Connection]]


class VapidKeysRepository:
    """CRUD for the vapid_keys singleton table.

    Args:
        connection_factory: no-arg callable returning a context manager that
            yields an open sqlite3.Connection (commit on clean exit, rollback
            on exception).
    """

    def __init__(self, connection_factory: ConnectionFactory) -> None:
        self._factory = connection_factory

    def get(self) -> VapidKeys:
        """Return the singleton row (id=1).

        Raises:
            RuntimeError: when the row is missing (get_or_create not called yet).

        Spec: SC-3.4
        """
        row = self._fetch()
        if row is None:
            raise RuntimeError(
                "vapid_keys row missing; call get_or_create() at startup"
            )
        return self._row_to_model(row)

    def get_or_create(self) -> VapidKeys:
        """Return existing row or generate a new NIST P-256 keypair and insert it.

        Idempotent: second call returns the same keypair. Concurrent first-boot
        races are handled by INSERT OR IGNORE + re-fetch.

        Spec: SC-3.1, SC-3.2
        """
        existing = self._fetch()
        if existing is not None:
            return self._row_to_model(existing)

        public_key_b64, private_key_pem = generate_keypair()
        now = datetime.now(UTC).isoformat()
        with self._factory() as conn:
            conn.execute(
                """
                INSERT OR IGNORE INTO vapid_keys (id, public_key, private_key, created_at)
                VALUES (1, ?, ?, ?)
                """,
                (public_key_b64, private_key_pem, now),
            )
        row = self._fetch()
        if row is None:
            raise RuntimeError("vapid_keys insert failed unexpectedly")
        return self._row_to_model(row)

    def public_key_uncompressed(self) -> str:
        """Return the raw uncompressed EC public key as URL-safe base64 (no padding).

        Decodes to exactly 65 bytes (0x04 || X || Y). Suitable for passing to
        pushManager.subscribe({applicationServerKey: urlBase64ToUint8Array(...)}).

        Spec: REQ-3.6, SC-3.3
        """
        keys = self.get()
        # The public_key column already stores the correct base64url format
        # as generated by vapid_keygen.generate_keypair().
        return keys.public_key

    def _fetch(self) -> Any:
        with self._factory() as conn:
            return conn.execute(
                "SELECT id, public_key, private_key, created_at FROM vapid_keys WHERE id = 1"
            ).fetchone()

    @staticmethod
    def _row_to_model(row: Any) -> VapidKeys:
        return VapidKeys(
            id=row[0],
            public_key=row[1],
            private_key=row[2],
            created_at=row[3],
        )
